[theme]
primaryColor = "#bd5c34"  # Medium slate blue (a bluish purple)
backgroundColor = "#FFFFFF"  # White
secondaryBackgroundColor = "#ffe3d8"  # Light cyan (a light bluish color)
textColor = "#28282b"  # Gray
font = "sans-serif" 

[server]
enableCORS = false
enableXsrfProtection = false
